### PR TITLE
Fix "Fixed deprecation warning in node test server"

### PR DESCRIPTION
**Pull request by guilliamxavier**
See https://github.com/guzzle/guzzle/pull/2517#discussion_r411423145

### CODE REVIEW

**Comment by gmponos** [comment]
Seems valid.. 
https://www.w3schools.com/nodejs/met_buffer_from.asp

**Comment by gmponos** [comment]
can you add the error that is reported by PHPStan into baseline in order to make the build pass?

**Comment by guilliamxavier** [comment]
@gmponos: done

**Comment by gmponos** [comment]
thank you.

**Pull request merged**
