### PR TITLE
Avoid PHPStan error

### PR DESCRIPTION
**Pull request by guilliamxavier**
See https://github.com/guzzle/guzzle/pull/2621#issuecomment-616472169

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: It should not be cast to a string. We want the code to crash if the returned value is not a string.

**Comment by GrahamCampbell** [comment]
This PR is replaced by https://github.com/guzzle/guzzle/pull/2626/files anyway, which adds this case to the baseline errors file.

**Comment by guilliamxavier** [comment]
Ok, please merge #2626 soon ;)

**Comment by guilliamxavier** [comment]
FTR: different approaches have been merged in #2638 (for `6.5`) and #2639 (for `master`)

**Comment by gmponos** [comment]
> FTR: different approaches have been merged in #2638 (for 6.5) and #2639 (for master)

Yea I know.. Personally speaking I want to keep the 6.5 with the minimum changes...

**Pull request closed without merging**
