### PR TITLE
fix dash underline for idn_conversion

### PR DESCRIPTION
**Pull request by jonnott**
...so it actually show in docs

### CODE REVIEW

**Comment by jonnott** [comment]
Current it shows as a failed section heading, and doesn't appear in the sidebar as it should .. 
image

**Comment by jonnott** [comment]
@sagikazarmark Can this be flagged for 6.5.1 milestone?

**Comment by alexeyshockov** [comment]
@jonnott, please use `6.5` branch (instead of `master`) if you want this change to be in the next fix release

**Comment by jonnott** [comment]
> @jonnott, please use `6.5` branch (instead of `master`) if you want this change to be in the next fix release

If I change base to 6.5 branch, I end up with an additional 25 commits from other people in the pull request .. do I need to make a different commit entirely on the 6.5 branch and then do a new PR?

**Comment by alexeyshockov** [comment]
> I end up with an additional 25 commits from other people in the pull request

Yes, because master is already ahead of `6.5`

> do I need to make a different commit entirely on the 6.5 branch and then do a new PR?

You could hard reset your branch to `6.5`, apply you changes and force push the changes... But a new PR (#2468) is also fine.

Please close this one then, because changes from `6.5` will be merged to master anyway.

**Comment by gmponos** [comment]
Thank you

**Pull request merged**
