### PR TITLE
Fix counting null variable (PHP 7.2)

### PR DESCRIPTION
**Pull request by scaytrase**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks, looks great. There are a few more places though where I could imagine this fix:

- static and normal constructor default value should be an empty array as well
- queue empty checks should use `empty` instead of just evaluating it as a boolean value

Can you do these fixes as well?

**Comment by scaytrase** [comment]
For more complex approach we should just add nightly php to travis test matrix (with allowed failures for some time) and see the failures. I can try it

**Comment by scaytrase** [comment]
Not sure about changing signatures as soon as it might provide any kind of BC breaks, but hardening checks sounds good

**Comment by sagikazarmark** [comment]
> For more complex approach we should just add nightly php to travis test matrix (with allowed failures for some time) and see the failures.

Agreed

> Not sure about changing signatures as soon as it might provide any kind of BC breaks, but hardening checks sounds good

Manually passing null to an array typehinted parameter is not possible in the first place, so I think changing the default value is safe in this case.

**Comment by scaytrase** [comment]
> Manually passing null to an array typehinted parameter is not possible in the first place, so I think changing the default value is safe in this case.

What about inheritance and `parent` calls? Most of classes are not final thus could be extended.

The following example fails on 7.1:

```php

class A
{
    public function __construct(array $val = [])
    {
        var_dump($val);
    }
}

class B extends A
{
    public function __construct(array $val = null)
    {
        parent::__construct($val);
    }
}

$b = new B();
```

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to A::__construct() must be of the type array, null given
```

So changing signature should be considered BC-break

**Comment by scaytrase** [comment]
Closing in favor of #1811

**Comment by sagikazarmark** [comment]
Hm, you are right :(

I thought this would fail too: https://3v4l.org/DWTTP

**Pull request closed without merging**
