### PR TITLE
Created more client exceptions

### PR DESCRIPTION
**Pull request by gmponos**
I have added some more Exceptions for 4xx http errors. I haven't wrote any Tests. If the changes seems fine to you then I will proceed with the unit tests and update any documentation.

More specific I added the following Exceptions

```
 400 = BadRequestException
 401 = UnauthorizedException
 403 = ForbiddenException
 404 = NotFoundException
 405 = MethodNotAllowedException
 406 = NotAcceptableException
 409 = ConflictException
 410 = GoneException
 429 = TooManyRequestsException
```

I believe they are the most common cases.

### CODE REVIEW

**Comment by gmponos** [comment]
Yes... It does add more maintenance and if it is ever needed to delete/change/refactor a class of them then it would be more easy to have a breaking change and I can see your point.

What I wanted to achieve is instead of having something like this:

``` php
    try {
        $client->get('/something');
    } catch(RequestException $e){
        if ($e->getCode() === 404){
            $this->doSomething();
        } else {
           $this->doSomethingElse();
       }
    }
    return false;
```

I think this it is better structured:
``` php
    try {
        $client->get('/something');
    } catch (NotFoundException $e){
        $this->doSomething();
    } catch (RequestException $e) {
       $this->doSomethingElse();
    }
    return false;
```

I am also curious about some feedback for this PR. So, yes... leave it open. Thank you.

**Comment by Konafets** [comment]
I like this. It gives some meaning to the status codes.

**Comment by Nyholm** [comment]
Thank you for this PR. 
I've discussed this back and forth many times. Though it seams nice there is no real reason for this when **catching** an exception. A third party library that uses Guzzle will not do anything different in the error handling if the response is a 404 or 405 exception. 

If an application author, however, is interested in a specific exception, I see no issue doing:
```php
try {
    $client->get('/something');
} catch(RequestException $e){
    $code = $e->getCode()
    if ($code === 404 || $code === 405){
        $this->checkTheHttpRequestLine();
    } elseif ($code > 410) {
       $this->doSomethingElse();
    } else {  
       $this->other();
    }
}
```

The benefits for this PR are small/none and it adds many more exception classes.

**Comment by ABM-Dan** [comment]
This might be better served by having the various codes available as constants instead of separate paper-thin classes.

**Comment by sagikazarmark** [comment]
Here you are: https://github.com/shrikeh/teapot

**Comment by sagikazarmark** [comment]
Thanks for the contribution @gmponos, but currently I don't see this acceptable for Guzzle, I am sorry.

**Comment by gmponos** [comment]
No problem.

**Pull request closed without merging**
