### PR TITLE
Logger context for the log middleware

### PR DESCRIPTION
**Pull request by scuben**
This PR adds the possibility to add a (static) context to the log message created by the guzzle middleware.

### CODE REVIEW

**Comment by gregurco** [comment]
@scuben what about failure case? why you don't use context there? On line 201.

**Comment by scuben** [comment]
@gregurco I added a test case covering the new implementation and added the context to the failure case.

**Comment by scuben** [comment]
Guess this is ready to merge, isn't it?

**Comment by sagikazarmark** [comment]
Thinking about this: I believe a better solution would be a decorator which adds default context to the log events.

Something like this:

```php
<?php

final class DefaultContextLogger implements \Psr\Log\LoggerInterface
{
    use \Psr\Log\LoggerTrait;

    private $logger;
    private $context = [];

    public function __construct(\Psr\Log\LoggerInterface $logger, array $context = [])
    {
        $this->logger = $logger;
        $this->context = $context;
    }

    public function log($level, $message, array $context = array())
    {
        $this->logger->log($level, $message, $this->context+$context)
    }
}
```

I would prefer keeping things simple.

**Comment by sagikazarmark** [comment]
Please refer to the solution above.

**Pull request closed without merging**
