### PR TITLE
Throwing errors because mark is not enrolled in github sponsors

### PR DESCRIPTION
**Pull request by hannesvdvreken**
Screenshot 2020-07-17 at 18 42 28

### CODE REVIEW

**Comment by gmponos** [comment]
Hi.

Even if it shows an error what's the problem with that? Does it block you from funding the rest of the maintainers? Otherwise I don't see any reason removing Mark.

**Comment by GrahamCampbell** [comment]
Well, if Mark doesn't have a sponsors account, maybe he wants to be funded in a different way. We should ask. :)

**Comment by hannesvdvreken** [comment]
@sagikazarmark Sign up! https://github.com/sponsors

**Comment by Nyholm** [comment]
Mark, let me know when you signed up and want to be on this list.

**Comment by sagikazarmark** [comment]
Sadly, GitHub sponsors is not available in Hungary. :(

**Pull request merged**
