### PR TITLE
Fix deprecations with guzzle/psr7 version 1.4

### PR DESCRIPTION
**Pull request by Tobion**
According to https://github.com/guzzle/psr7/releases/tag/1.4.0

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks @Tobion 

I would probably wait for guzzle/psr7#138 to get to a resolution before merging. What do you think?

Also, should this go into a patch release or can be part of 6.3 which is imminent, but probably still needs a few weeks.

**Comment by sagikazarmark** [comment]
Although it seems like the changes in this PR are not affected by the BC break being discussed in the aformentioned issue, are they?

**Comment by Tobion** [comment]
This PR is independent of https://github.com/guzzle/psr7/issues/138 and can be merged regardless.

**Comment by sagikazarmark** [comment]
This will be merged and released as 6.2.3 soon. The base needs to be changed though.

**Pull request closed without merging**
