### PR TITLE
fix NTLM auth support

### PR DESCRIPTION
**Pull request by Sebascii**

### CODE REVIEW

**Comment by Sebascii** [comment]
added CURLAUTH_NTLM  http auth option

$client = new Client([
        'base_uri' => $url,
        'auth'    => array($user, $password 'ntlm')
    ]);

**Comment by jeskew** [comment]
Is there any way to support NTLM that will work with the stream handler?

**Comment by mtdowling** [comment]
Please update this PR with tests, documentation, and this would require throwing an exception in the StreamHandler because it does not support ntlm.

**Comment by sagikazarmark** [comment]
@Sebascii  Should this be closed in favor of #1569?

**Comment by sagikazarmark** [comment]
Thanks for your contribution, but I merged #1569 which implemented the same feature.

**Pull request closed without merging**
