### PR TITLE
Clean up gitignore add adding PHPUnit

### PR DESCRIPTION
**Pull request by Nyholm**
Follow up from #2430

FYI @gmponos

### CODE REVIEW

**Comment by gmponos** [comment]
Great I was also wondering why this is needed `composer-test.lock`

🤔

**Comment by Nyholm** [comment]
What is `composer-test.lock`?

**Comment by gmponos** [comment]
don't know either.. it is inside gitignore...

**Comment by Nyholm** [comment]
Oh =)

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
