### PR TITLE
Adding some highly opinionated CS fixes

### PR DESCRIPTION
**Pull request by Nyholm**
Basically: 
- If a method has 3 or less arguments, lets not do them on multiple lines. 
- Make sure lines are readable rather than short. 
- Make exceptions on one line

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The rule I usually use is 120 characters is fine for single line, but behond that, make multiline. That is instead of "3 params on one line".

**Comment by mfn** [comment]
No automation tools for this exist, do they?

**Comment by GrahamCampbell** [comment]
Single line exceptions can be enforced by php-cs-fixer.

**Comment by Nyholm** [comment]
I know that there is a rule like that, but we are currently not enforcing it. I just took the simple methods that were split into multiple lines and made them more readable.

**Comment by TimWolla** [comment]
As a tiny data point: I agree with this change. It's much more readable.

**Pull request merged**
