### PR TITLE
Fixed a PHP namespace

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The example is already fine without this surely? The example is not namespaced.

**Comment by javiereguiluz** [comment]
@GrahamCampbell if line 21 is correct, then should we update the line 33? Thanks.

**Comment by GrahamCampbell** [comment]
Looks like line 33 has an unnecessary slash too.

Best leave it to @mtdowling to decide what he wants though. :)

**Comment by Tobion** [comment]
:+1: good this way

**Pull request merged**
