### PR TITLE
PSR-2

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by mtdowling** [comment]
I haven't checked recently, but I don't think PSR-2 has any guidance specifically around empty interfaces.

**Comment by hannesvdvreken** [comment]
CS-fixer level psr-2 puts them like this. Opening brackets always go on the next line.

**Comment by hannesvdvreken** [comment]
But it's your call, just proposing it here.

**Comment by mtdowling** [comment]
Instead of a lot of one-off code formatting PRs, I'd be more open to discussing a more general PSR-2 update. Closing this.

**Comment by hannesvdvreken** [comment]
Yeah, good idea. What would you be open to? A `.php_cs` file or a `scrutinizer.yml` file for checking and a big PR to fix all small inconsistencies? That might be hard to merge because of open PRs that will give merge conflicts then.

**Pull request closed without merging**
