### PR TITLE
[7.1] Deprecate the getConfig method

### LINKED ISSUE #2514: [RFC] Deprecate getConfig
I feel like the client configuration should be immutable, and should not be exposed to the outside, either to be read, or to be changed. Should we mark `getConfig` on the client interface as deprecated in 7.x, and remove it in 8.0.0?

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This depends on https://github.com/guzzle/guzzle/pull/2515 being merged first.

---

Closes #2514.

### CODE REVIEW

**Comment by gmponos** [comment]
I suggest to move this discussion for 7.1

**Comment by sagikazarmark** [comment]
Like the idea, but I agree we should move this to 7.1 with the rest of the deprecations.

**Comment by GrahamCampbell** [comment]
Sure. It would be great if #2515 could be merged earlier, so that the docs don't show using a function we plan to deprecate, and neither does our test code. That's why I separated it into two PRs. ;)

**Comment by Nyholm** [comment]
I agree to deprecate this function.

**Comment by Nyholm** [comment]
Sorry for the long delay. Could you please rebase this PR?

**Pull request merged**
