### PR TITLE
Adding protocol when missing from the url

### PR DESCRIPTION
**Pull request by alex-moreno**
As per issue https://github.com/guzzle/guzzle/issues/1656

### CODE REVIEW

**Comment by alex-moreno** [comment]
um, not sure how to solve this

```Argument 1 of strpos expects string, Psr\Http\Message\UriInterface provided with a __toString method```

**Comment by alex-moreno** [comment]
> um, not sure how to solve this
> 
> `Argument 1 of strpos expects string, Psr\Http\Message\UriInterface provided with a __toString method`

actually fixed

**Comment by GrahamCampbell** [comment]
Is omitting the protocol even permitted by the HTTP spec? If not, I don't think we should support it, and people need to fix their server implementations.

**Comment by alex-moreno** [comment]
> Is omitting the protocol even permitted by the HTTP spec? If not, I don't think we should support it, and people need to fix their server implementations.

Good point

**Review by Nyholm — CHANGES_REQUESTED** [review]
what if Im redirected to `tcp://` or ´foobar://´

I vote for closing this.

**Comment by GrahamCampbell** [comment]
I agree with @Nyholm.

**Comment by GrahamCampbell** [comment]
Thanks for your time preparing this PR, but we don't feel that it is something we should support.

**Pull request closed without merging**
