### PR TITLE
Adding on_redirect. Addresses #1166

### PR DESCRIPTION
**Pull request by mtdowling**

### CODE REVIEW

**Comment by dawehner** [comment]
Looks fine for me. Thank you for being so responsive!

**Comment by larowlan** [comment]
:+1: 

Thanks!
Much nicer than my workaround
```php
$stack->after('allow_redirects', Middleware::mapRequest(function (RequestInterface $request) {
      $this->effectiveUrl = $request->getUri();
      return $request;
    }), 'check_redirect');
    $stack->after('allow_redirects', Middleware::mapResponse(function (ResponseInterface $response) {
      return $response->withHeader('X-Effective-Url', (string) $this->effectiveUrl);
    }), 'store_redirect');
```

**Comment by jibran** [comment]
+1

**Comment by pfrenssen** [comment]
Linking issue #1166.

**Pull request merged**
