### PR TITLE
Use final annotation to mark classes as final

### PR DESCRIPTION
**Pull request by gmponos**
Mark classes as final

### CODE REVIEW

**Comment by gmponos** [comment]
This is related with #2725  and it also closes #2521

**Comment by gmponos** [comment]
Are there more classes that we should mark as final?

**Comment by GrahamCampbell** [comment]
I think this is enough for now. You'll need to remove that extra entry from the phpstan baseline file too. ;)

**Comment by vaclavvanik** [comment]
MessageFormatter does not implement interface. If it will be final there is no way have to use own implementation.

**Comment by GrahamCampbell** [comment]
> MessageFormatter does not implement interface. If it will be final there is no way have to use own implementation.

Why would someone want to extend that class, though?

**Comment by GrahamCampbell** [comment]
If you wanna have your own formatter class, it doesn't need to extend Guzzle's. You can just call the public API of the original class from your new class, without needing to extend it.

**Comment by gmponos** [comment]
> If you wanna have your own formatter class, it doesn't need to extend Guzzle's. You can just call the public API of the original class from your new class, without needing to extend it.

But you can't inject your custom class into the log middleware.. there might be some value having an interface for `MessageFormatter`.

Would appreciate any feedback on that.

**Comment by GrahamCampbell** [comment]
Hmmm, that's true. Is anyone actually using a custom impl?

**Comment by vaclavvanik** [comment]
Actually I use my own implementation. Currently I extend MessageFormatter
because there is no interface. My use case is that I do not log message
body greater than 64 kB.

Dne ne 12. 7. 2020 11:33 uživatel Graham Campbell <notifications@github.com>
napsal:

**Comment by GrahamCampbell** [comment]
Ok, so I think we can still add the soft final annotation, but we also should add a `MessageFormatterInterface` and change the type on the log middleware to that, which shouldn't be a breaking change.

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
