### PR TITLE
https://github.com/guzzle/guzzle/issues/1256

### PR DESCRIPTION
**Pull request by daleattree**
Code added to resolve issue 1256

### CODE REVIEW

**Comment by mtdowling** [comment]
Looks like a test failure.

**Comment by daleattree** [comment]
Added an incorrect assertion into the test. Apologies for that. Tests are working.

**Comment by mtdowling** [comment]
Can you add a test or update an existing test to ensure that this value is set to false when verify is set to false?

**Comment by daleattree** [comment]
StreamHandlerTest.php updated to ensure both true and false for SSL verify_peer_name

**Comment by mtdowling** [comment]
Should a test be added to https://github.com/guzzle/guzzle/pull/1286/files#diff-25965a11c4d928e67905c6d782fa52e3R230 that asserts that `verify_peer_name` was set to `false`?

**Comment by Blackout** [comment]
I've added some code that handles the SSL Stream Context Options in my pull request

The Tests have been updated too

https://github.com/guzzle/guzzle/pull/1298

**Pull request merged**
