### PR TITLE
Update Client.php

### PR DESCRIPTION
**Pull request by fhferreira**
Force Line 310 params to be array:
$result = $options + $defaults;

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please upgrade to Guzzle 7.4.1.

**Comment by fhferreira** [comment]
@GrahamCampbell even updating it I am still receiving:
image

**Comment by fhferreira** [comment]
only $options exists, but no $defaults.

**Comment by fhferreira** [comment]
image

**Comment by fhferreira** [comment]
image

**Comment by fhferreira** [comment]
image

**Pull request closed without merging**
