### PR TITLE
Create the important method "createRequest"

### PR DESCRIPTION
**Pull request by nadavvin**
GuzzleHttp\Psr7\Request allow to create Request instance but it not handle guzzle options

### CODE REVIEW

**Comment by nadavvin** [comment]
Not really needed

**Comment by nadavvin** [comment]
I reopen since it might still needed because for method like ->post() can get json array in body, but it is not happen in PSR Request.

So if this is possible solution ir you change Request to recognize 'json' key in body params

**Comment by sagikazarmark** [comment]
I don't really think I want to expose request creation that way. It contains a lot of internal logic.

You can create your own request as easy as just encoding the body to json manually.

**Comment by nadavvin** [comment]
It is not only json, what about query option. I need to escape the params myself while it not necessary to do in direct request like ->get()

**Comment by Nyholm** [comment]
Im also 👎 

There is no need to have a method for creating `Request`s

**Comment by nadavvin** [comment]
What about file upload? at least need helper methods to create the body...

**Pull request closed without merging**
