### PR TITLE
Fixing issue #1528 - default value of allow_redirects.referer

### PR DESCRIPTION
**Pull request by mstrom**
Issue #1528

### CODE REVIEW

**Comment by mtdowling** [comment]
Thanks for the PR!

In this case, I think I'd actually rather update the documentation to reflect the code rather than the code to reflect the docs.

**Comment by mstrom** [comment]
@mtdowling are you sure? Curl has referer option (CURLOPT_AUTOREFERER) set to true on default

http://php.net/manual/en/function.curl-setopt.php

**Comment by mtdowling** [comment]
Yeah, curl doesn't have this default behavior from what I can tell. I'm also hesitant to start sending this data with redirects when we haven't always done that.

**Comment by mstrom** [comment]
@mtdowling I changed documentation please review

**Comment by mtdowling** [comment]
thanks!

**Pull request merged**
