### PR TITLE
CS fixes (phpdoc_align)

### PR DESCRIPTION
**Pull request by Nyholm**
FYI @gmponos

### CODE REVIEW

**Comment by gmponos** [comment]
1. Do we keep superfluous docblocks https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:no_superfluous_phpdoc_tags
2. I would suggest also these:

https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:no_blank_lines_after_phpdoc
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_trim_consecutive_blank_line_separation
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_trim
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_var_without_name
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_scalar
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_types
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_single_line_var_spacing

3. I don't like this.. but I see it used inside the codebase:
https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:phpdoc_separation

Also I added some on another PR that it is now merged due to PHPUnit docblock changes...

**Comment by Nyholm** [comment]
I updated the PHPStan baseline because removing `@return mixed` got PHPStan upset.

**Comment by Nyholm** [comment]
Thank you @gmponos I've added the styles you suggested.

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
