### PR TITLE
#2318 wildcard for matches to any domain

### PR DESCRIPTION
**Pull request by 4n70w4**

### CODE REVIEW

**Comment by 4n70w4** [comment]
https://github.com/guzzle/guzzle/pull/2317

**Comment by Nyholm** [comment]
Closing due inactivity. Feel free to comment on this PR if you change your mind.

**Comment by 4n70w4** [comment]
@Nyholm inactivity? What activity did you expect from me?

**Comment by Nyholm** [comment]
I expected you to answer questions an elaborate why this is needed. 

See https://github.com/guzzle/guzzle/pull/2317#issuecomment-543697314

**Comment by Nyholm** [comment]
It is not closed forever. Feel free to answer the questions now and we can reopen the PRs and issues.

**Pull request closed without merging**
