### PR TITLE
Test with prefer lowest

### PR DESCRIPTION
**Pull request by Nyholm**
This PR shows that https://github.com/guzzle/guzzle/pull/1713 is needed. 

This is related to https://github.com/guzzle/RingPHP/issues/39

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Can you please rebase?

**Comment by Nyholm** [comment]
Of course. PR is rebased and tests are passing

**Comment by sagikazarmark** [comment]
Thanks

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
