### PR TITLE
added trim BOM (for some response from bad .Net)

### PR DESCRIPTION
**Pull request by andboson**

### CODE REVIEW

**Comment by kamilsk** [comment]
like https://github.com/guzzle/guzzle/pull/1041

-1

**Comment by andboson** [comment]
@kamilsk what about bom in beginning of file?

and preg...always should find to how use string functions instead regexp

**Comment by kamilsk** [comment]
Presence of the BOM at the beginning of the file is a special case (specific for "bad .Net").
You can remove it like this.
```php
$responseBody = json_decode((string) $response->getBody(), ...options);
```
Special cases will be resolved privately. IMO

**Comment by andboson** [comment]
I want use existing function jsonDecode with error handling, etc.

**Comment by kamilsk** [comment]
You can do this:
```php
try {
    $responseBody = \GuzzleHttp\Utils::jsonDecode(str_replace("\xEF\xBB\xBF", '', (string) $response->getBody()), ...options);
} catch (...handle required exception) {
}
```

**Comment by kamilsk** [comment]
or you want to use `$response->json()` ?

**Comment by andboson** [comment]
yep

**Comment by kamilsk** [comment]
@andboson, how about event listeners? just modify body (remove bom) after success response and use `->json` you want.

**Pull request closed without merging**
