### PR TITLE
Date format to match Apache Common Log

### PR DESCRIPTION
**Pull request by rtheunissen**
Small update to match the referenced log format.

### CODE REVIEW

**Comment by mtdowling** [comment]
Heh. I just beat you to it :)

**Comment by mtdowling** [comment]
See https://github.com/guzzle/guzzle/commit/861d2da555ebe00a036235700291793d6d554b79

**Comment by rtheunissen** [comment]
Wasn't much of a race, but thanks for making the change. :) You could change the doc reference link to match Apache 2.4 (currently it points to 1.3) even though nothing seems to have changed. Nice to keep up to date regardless.

**Comment by mtdowling** [comment]
Ah good point. I'll update the link. Thanks!

**Pull request closed without merging**
