### PR TITLE
BASE_URI constant to \GuzzleHttp\RequestOptions

### PR DESCRIPTION
**Pull request by 4n70w4**
https://github.com/guzzle/guzzle/issues/2283

### CODE REVIEW

**Comment by drull755** [comment]
Hehe))
https://github.com/guzzle/guzzle/pull/2291

**Comment by 4n70w4** [comment]
@drull755 your description in the comment is more informative =)

**Comment by rtek** [comment]
base_uri is not a request option because passing it in a request call will not alter the client behavior.

**Comment by 4n70w4** [comment]
@rtek and what do you suggest? Create a new class for the sake of 1 constant?

**Comment by rtek** [comment]
Add it to Client along with handler or leave it be.

**Comment by Nyholm** [comment]
Closing due inactivity. 

Thank you for the PR and the reviews.

**Comment by 4n70w4** [comment]
@Nyholm what activity did you expect?

**Comment by Nyholm** [comment]
I expected a response to @rtek comments.

**Pull request closed without merging**
