### PR TITLE
Do not connect a sink for HEAD requests

### PR DESCRIPTION
**Pull request by TimWolla**
This PR was created in response to the test discussion in #2741: https://github.com/guzzle/guzzle/pull/2741#issuecomment-698808528

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
I agree with this. 

@GrahamCampbell do you have any comments?

(here is a better [diff](https://github.com/guzzle/guzzle/pull/2778/files?diff=unified&w=1))

**Comment by GrahamCampbell** [comment]
Does a similar change need to be made to the stream handler?

**Comment by TimWolla** [comment]
> Does a similar change need to be made to the stream handler?

It appears as if a check for HEAD requests is already implemented there, making the answer to your question “no”. That one uses strcasecmp, though: https://github.com/guzzle/guzzle/blob/7881628c7fd44078a4d33376fe9cef23dcd26b4f/src/Handler/StreamHandler.php#L120

Should I adjust CurlFactory to make use of `strcasecmp`?

**Comment by TimWolla** [comment]
> Should I adjust CurlFactory to make use of `strcasecmp`?

As discussed with nyholm on php-http Slack: The use of `strcasecmp` technically is incorrect, because the HTTP method is case sensitive. That comparison will not be fixed, but I won't introduce any more case-insensitive comparisons.

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
