### PR TITLE
Support PHP 8.1

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Great. Thank you!

**Comment by driesvints** [comment]
Hey @GrahamCampbell @Nyholm. Can we get these changes tagged? Thanks!

**Comment by GrahamCampbell** [comment]
Waiting on a tag on the psr7 library, first. Still a PR over there that needs to be merged.

**Comment by driesvints** [comment]
Which PR?

**Comment by GrahamCampbell** [comment]
"just" need to write a change log. :P

**Comment by wouter-toppy** [comment]
@Nyholm  can we merge the changes also in Guzzle 6.x?

src/Handler/MockHandler.php.

```
PHP Fatal error:  Uncaught Symfony\Component\ErrorHandler\Error\FatalError: Error: During inheritance of Countable: Uncaught Behat\Testwork\Call\Exception\CallErrorException: 8192: Return type of GuzzleHttp\Handler\MockHandler::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/guzzlehttp/guzzle/src/Handler/MockHandler.php line 173
```

We have our WMS still at Guzzle6 `6.5.8` 
But we are almost ready to go to PHP8.1. 

But upgrading to guzzle7 is not possilble at the moment, given we are waiting on several third party repos to implement 7 as well. 
(like https://github.com/swagger-api/swagger-codegen/issues/11123)

**Comment by GrahamCampbell** [comment]
No. Guzzle 6 does not support PHP 8.1.

**Pull request merged**
