### PR TITLE
Declare compatibility with PHP 8

### PR DESCRIPTION
**Pull request by pfrenssen**
Let's see if we have any failures on PHP 8.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It is much too early to do this. We should review this later in the Guzzle 7.x series.

**Comment by pfrenssen** [comment]
I agree that it is too early, Guzzle 7 would be a good target and we also need to wait until our dependencies are PHP 8 compatible.

I'm posting this as a counterproposal for #2664 - this is an exercise to discover a good practice for supporting PHP 8 early on. I think the proposal in #2664 to set a version constraint like `>=7` is risky and unneeded.

For now I am curious how Guzzle fares on PHP 8. I will close this when I'm done experimenting.

**Comment by pfrenssen** [comment]
Awesome, it seems we are mostly compatible with PHP 8 already. There are a few failures but they are all related to a single line in `guzzlehttp/promises` which throws the following:

```
TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

##[error]/home/runner/work/guzzle/guzzle/vendor/guzzlehttp/promises/src/Promise.php:151
```

So it appears we should wait here until promises is PHP 8 ready :)

**Comment by GrahamCampbell** [comment]
Yeh, there are some known issues with both our promises library and react's one. The will both be fixed in good time. :)

**Pull request closed without merging**
