### PR TITLE
Fix "curl error msg for low version"

### PR DESCRIPTION
**Pull request by guilliamxavier**
Rework of #2648 for 7.x as requested there

### CODE REVIEW

**Comment by Nyholm** [comment]
Sorry for the long delay. Could you please rebase this PR?

**Comment by guilliamxavier** [comment]
@Nyholm: No worries, rebased

**Comment by GrahamCampbell** [comment]
Note that once Guzzle eventually drops PHP 7, this minimum libcurl version check can go. https://github.com/php/php-src/blob/master/UPGRADING#L771

**Comment by guilliamxavier** [comment]
@GrahamCampbell: this version check was dubious in the first place, and this PR makes the `LOW_CURL_VERSION_NUMBER` constant unused and deprecated, to be removed in Guzzle 8.0.0 (regardless of the supported PHP/libcurl version)

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
