### PR TITLE
[WIP] [7.0] Default connect_timeout on curl to 300 seconds

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes https://github.com/guzzle/guzzle/pull/1524.

### CODE REVIEW

**Comment by Nyholm** [comment]
Awesome. Thank you!

**Comment by GrahamCampbell** [comment]
Just pushed another change here.

**Comment by Nyholm** [comment]
Im trying to find where we define the default timeout for the stream. 

Could you show me? I want to verify that we have the same timeout.

**Comment by GrahamCampbell** [comment]
The stream handler doesn't have a connect timeout, since it's not supported by the handler. It only has a "timeout".

**Comment by Nyholm** [comment]
Yeah, but we dont sent at default value for the "timeout", are we?

**Comment by GrahamCampbell** [comment]
Ah, yeh. What do we want for a timeout value?

**Comment by GrahamCampbell** [comment]
Default "timeout" to "infinity", and "connect timeout" to "300 seconds"?

**Comment by Nyholm** [comment]
Is this correct?

### Curl: 
- Connect timeout: 300s (changed in this PR)
- Timeout: infinity
- Read timeout: default_socket_timeout

### Stream:
- Connect timeout: 300s (cannot be configured)
- Timeout: infinity
- Read timeout: default_socket_timeout

**Comment by GrahamCampbell** [comment]
No. I don't think the stream handler has a concept of a connect timeout. I'm not too sure.

**Comment by GrahamCampbell** [comment]
There is `stream_set_timeout`, which defaults to 60 seconds. That is what controls how long we wait between receiving the last byte, and timing out, I think. Maybe that controls the connect timeout too?

**Comment by Nyholm** [comment]
The goal of this PR should be that this code:

```php
// Will block for X seconds
$client->get('https://no-url.com');

```

should be blocking for X seconds. No matter if one use the curl handler or the socket handler. Since curl is way more configurable. We should look at what we can configure in the socket handler, then set sensible defaults and mimic those settings in curl. 

So the first thing we need to figure out how socket behave.

**Comment by kkopachev** [comment]
This ticket related to #2539

**Comment by kkopachev** [comment]
For streams:
looks like when using `fopen` with `http` handler, `connect_timeout` defaults to `default_socket_timeout`. Then if context resource is passed with configured `http => timeout` value, it is used as `read timeout`. 

Here is my path of thought:

`fsockopen` (unlike `fopen`) can receive connect [timeout as parameter](https://www.php.net/manual/en/function.fsockopen.php) which defaults to [default_socket_timeout](https://github.com/php/php-src/blob/d1764ca33018f1f2e4a05926c879c67ad4aa8da5/ext/standard/fsock.c#L34). It is only used as connect_timeout. Then it passed to [php_stream_xport_create](https://github.com/php/php-src/blob/d1764ca33018f1f2e4a05926c879c67ad4aa8da5/ext/standard/fsock.c#L72-L81) as parameter, which handles socket connection and etc and returns stream.

`fopen` with http handler reads timeout value [from context options](https://github.com/php/php-src/blob/5d6e923d46a89fe9cd8fb6c3a6da675aa67197b4/ext/standard/http_fopen_wrapper.c#L195), defaulting to [default_socket_timeout](https://github.com/php/php-src/blob/5d6e923d46a89fe9cd8fb6c3a6da675aa67197b4/ext/standard/http_fopen_wrapper.c#L208) ini setting. Then it passes timeout value to the same [php_stream_xport_create](https://github.com/php/php-src/blob/5d6e923d46a89fe9cd8fb6c3a6da675aa67197b4/ext/standard/http_fopen_wrapper.c#L213-L215) and opens the stream. After successful opening and connection, it [sets read timeout](https://github.com/php/php-src/blob/5d6e923d46a89fe9cd8fb6c3a6da675aa67197b4/ext/standard/http_fopen_wrapper.c#L218) to the same timeout value which was passed as context option. 
From my understanding, it is possible to change read_timeout for open stream by calling `stream_set_timeout`. However, that might be too late already, since php handled sending request headers, received  response headers and at the beginning of data stream (or possibly read some of it already into buffer).

**Comment by mfn** [comment]
?

**Comment by GrahamCampbell** [comment]
Closed because the implementation was not right, and it's not clear what the right implementation is. There is already an open issue tracking this bug, so closing this doesn't hide that issue.

**Pull request closed without merging**
