### PR TITLE
limit connections to host

### PR DESCRIPTION
**Pull request by Gemorroj**
Not a very nice fix for #2248.
But at least something.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Wouldn't using `'curl'` [request option](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L51) be a solution?

**Comment by Gemorroj** [comment]
@sagikazarmark this options for `curl_init`, not for `curl_multi_init` https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlMultiHandler.php#L50

**Comment by alexeyshockov** [comment]
IMO we need a more elegant solution for that. A new option `curl_multi` (like `curl`, but for `curl_multi_init()`/`curl_multi_setopt()`) is more flexible, since there are many `CURLMOPT_*` configuration constants available.

**Comment by alexeyshockov** [comment]
@sagikazarmark, @Gemorroj, put some code in #2287. Take a look.

**Comment by Tobion** [comment]
#2287 looks better to me indeed

**Pull request closed without merging**
