### PR TITLE
GitHub Workflows security hardening

### PR DESCRIPTION
**Pull request by sashashura**
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or action) is restricted.
It is recommended to have [most strict permissions on the top level](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) and grant write permissions on [job level](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) case by case.

### CODE REVIEW

**Comment by Zombaya** [comment]
@sashashura , I noticed you are creating PR's like this to a lot of high profile projects and wanted to express my gratitude for trying to create a safer environment for the general public by having major projects increase the security.

I'm no maintainer to this project, so I will not be able to help with this particular PR but just wanted to send good vibes your direction.

Kudos!

I can see you automated the creation of this PR's a bit, so it might be interesting to add a link to your project in the text of your PRs or star it on your profile in some way so others might contribute or learn from it.

**Comment by GrahamCampbell** [comment]
It's a shame that GitHub can't provide more secure defaults, and I'm reluctant to merge this in case there are product changes coming down the line.

**Comment by GrahamCampbell** [comment]
I am waiting for feedback from a contact I have on GitHub r.e. this.

**Comment by GrahamCampbell** [comment]
They have now changed the product: https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/.

**Pull request merged**
