### PR TITLE
Fixed native_function_invocation CS

### PR DESCRIPTION
**Pull request by Nyholm**
This will replace #2401

### CODE REVIEW

**Comment by gmponos** [comment]
Shouldn't the php_cs file contain changes?

**Comment by Nyholm** [comment]
No, because we cannot use this all over the place. 

See `bootstrap.php`: We rely on overriding these functions in the tests. 

```php
// Override curl_setopt_array() and curl_multi_setopt() to get the last set curl options
namespace GuzzleHttp\Handler {
    function curl_setopt_array($handle, array $options)
    {
        if (!empty($_SERVER['curl_test'])) {
            $_SERVER['_curl'] = $options;
        } else {
            unset($_SERVER['_curl']);
        }
        return \curl_setopt_array($handle, $options);
    }

    function curl_multi_setopt($handle, $option, $value)
    {
        if (!empty($_SERVER['curl_test'])) {
            $_SERVER['_curl_multi'][$option] = $value;
        } else {
            unset($_SERVER['_curl_multi']);
        }
        return \curl_multi_setopt($handle, $option, $value);
    }
}

```

**Comment by gmponos** [comment]
I would have approved this.. but I am still wondering why symfony (hope I have understood correctly) does not prefix all the functions.. 

I am not saying we should follow it just because they do it.. but I am wondering if there is a performance reason that we are not aware or if it is for BC reason (easier MRs)

**Comment by Nyholm** [comment]
I don’t 100% know. But I’m sure it is because Symfony wants to avoid merge conflicts when merging bug fixes between the 3-4 active branches.

**Comment by GrahamCampbell** [comment]
Yes, probably. Also, once you prefix a function, it makes it impossible to mock, so things like `microtime` can no longer be mocked by the strategy of defining a function in the other namespace of the same name, if it has been prefixed with a slash.

**Comment by Nyholm** [comment]
Note also that "impossible to mock" means that it is more secure sine no evil package maintainer may change the functionality of native methods.

**Comment by GrahamCampbell** [comment]
> Note also that "impossible to mock" means that it is more secure sine no evil package maintainer may change the functionality of native methods.

Well, yeh. But also, impossible for the package's own tests to mock functions, if they wanted to.

**Comment by Nyholm** [comment]
Thank you for the reviews and discussion.

**Pull request merged**
