### PR TITLE
[7.1] Deprecate Utils::defaultCaBundle

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Requires https://github.com/guzzle/guzzle/pull/2561 to be merged first. Is a follow up to https://github.com/guzzle/guzzle/pull/2560.

### CODE REVIEW

**Comment by gmponos** [comment]
Well you say in the title that you deprecate only one function but I see more... are the commits correct?

**Comment by gmponos** [comment]
If we removed the usages of `defaultCaBundle` by merging `https://github.com/guzzle/guzzle/pull/2560` why should we deprecate a function that it is not tagged? Do I miss something?

**Comment by GrahamCampbell** [comment]
Because the function might be still used by people outside of the guzzle core code, since it's not marked as internal. Safest to deprecate in 7.1 and remove in 8.0, I think?

**Comment by gmponos** [comment]
@GrahamCampbell sorry my initial comment was confusing.. let me clarify..

this function: https://github.com/guzzle/guzzle/pull/2562/files#diff-8196fda03bd99e941e07599792a645a4R137

is not tagged.. why should it be deprecated?

**Comment by Nyholm** [comment]
Sorry for the long delay. Could you please rebase this PR?

**Comment by Nyholm** [comment]
Pleas rebase so I can merge.

**Comment by Nyholm** [comment]
It seams like this includes changes from #2561

**Comment by GrahamCampbell** [comment]
Yes, this PR does. It can only be processed after that first PR is finished and merged. This PR depends on it.

**Comment by GrahamCampbell** [comment]
Yes, because it depends on the other PR being merged first. Notice how https://github.com/guzzle/guzzle/pull/2562/commits/53c9ac53b7dc865174c6697f95e63c787580580e changes a deprecation message from one of the functions.

**Comment by GrahamCampbell** [comment]
Sorted this out now. :)

**Pull request merged**
