### PR TITLE
7.0

### PR DESCRIPTION
**Pull request by fhferreira**

### CODE REVIEW

**Comment by fhferreira** [comment]
image
image
image
image

**Comment by GrahamCampbell** [comment]
Please target 7.4.x?

**Comment by fhferreira** [comment]
> Please target 7.4.x?

How can I do it @GrahamCampbell ?

**Comment by fhferreira** [comment]
image
My current installed release is: 7.4.1 but the branch is 7.0, no?

**Comment by GrahamCampbell** [comment]
The branch is called master. The 7.0 branch is for the 7.0.x series, not 7.x.

**Comment by GrahamCampbell** [comment]
I am not sure this bug is actually a bug - I think it's more likely you have an old install of guzzle globally, as well as your local install.

**Comment by GrahamCampbell** [comment]
It is impossible for options not to be an array.

**Comment by fhferreira** [comment]
@GrahamCampbell the weird, is that we start to receive that error in the latest christmas, it reach 1M of issues in sentry

**Comment by fhferreira** [comment]
but confirming that "default/options" were really array, just to prevent the error, and check if the rest will works like ever.

**Comment by fhferreira** [comment]
thanks man. Pointed to master

**Pull request closed without merging**
