### PR TITLE
Bugfix/curlopt capath

### PR DESCRIPTION
**Pull request by notxarb**
This should resolve issue #1683

### CODE REVIEW

**Comment by geradt** [comment]
When will this fix be committed and merged with master (released)?

I am having an issue right now that this solution would resolve.

**Comment by sagikazarmark** [comment]
If you need an immediate solution you can copy the propsed factory to your code base and use it in your curl handler.

This PR will be reviewd shortly.

**Comment by geradt** [comment]
Hi Just checking in on this fix again. Any chance it can go in the next push? Thank you again in advance.

**Comment by sagikazarmark** [comment]
@geradt  i will try to make it in the next (6.3) release, but I would like to check if the file/dir checks are correct first.

**Comment by geradt** [comment]
Thank you! The sooner you can get this in the better. I appreciate it. Do you have any kind of target date in mind? I see the 6.3 milestone but it doesn't have a due date.

Thanks!

**Comment by sagikazarmark** [comment]
I would like to get it done asap, but time is a factor I have to take into account sadly.

**Comment by sagikazarmark** [comment]
Thanks for your patience and work. 6.3 is not so far.

**Comment by geradt** [comment]
Thanks sagikazarmark!! Looking forward to it!

**Pull request merged**
