### PR TITLE
Update Client.php

### PR DESCRIPTION
**Pull request by jezemery**
Fix a typo in the InvalidArgumentException thrown for invalidBody

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you.

**Comment by sagikazarmark** [comment]
Thanks for your contribution.

I have one request though: Can you please write more meaningful commit messages than "Update Client.php"?

**Comment by Nyholm** [comment]
Sorry, I was to fast on the merge button.

**Comment by sagikazarmark** [comment]
NP

**Pull request merged**
