### PR TITLE
Fix invalid character regex

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by mtdowling** [comment]
Can you get the tests passing? Once they're passing, I'll merge.

**Comment by sagikazarmark** [comment]
Can you please restart the build: composer failed now.

**Comment by mtdowling** [comment]
Restarted

**Comment by sagikazarmark** [comment]
Tests are fixed. Should I squash?

**Comment by mtdowling** [comment]
Thanks! Looks good.

**Pull request merged**
