### PR TITLE
Test on Windows PHP 8.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Errrrrr:

image

**Comment by TimWolla** [comment]
As of RC 2 the test works. See: https://github.com/TimWolla/guzzle/pull/1

**Review by TimWolla — APPROVED** [review]

**Comment by GrahamCampbell** [comment]
> As of RC 2 the test works.

RC2 is not what is being tested on here. It is nightly builds of the PHP-8.0 branch.

**Comment by Nyholm** [comment]
Cool cool cool. 

No more segfaults =)

**Comment by TimWolla** [comment]
@Nyholm You probably want to actually push an approving review here :smiley:

**Review by Nyholm — APPROVED** [review]
Awesome. Tests are green now

**Pull request merged**
