### PR TITLE
Restore ^ to symfony/polyfill-intl-idn version

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by gmponos** [comment]
Hi.. there is also this: https://github.com/guzzle/guzzle/pull/2663

Let's keep the discussion there.. and let us know your feedback. 😄

**Comment by reedy** [comment]
Breaking change for me was the removal of the `^`, meant the `replace` directive in composer.json didn't work (using a version of 1.99). We don't need this polyfill as we install php-intl/ext-intl. Sure it's easily fixed by just changing the replace from 1.99 to 1.17.0, but it's not very future proof, and if another library has a different require constraint... It gets awkward :)

**Comment by GrahamCampbell** [comment]
👎 to this solution, because we are using internal code, and semver breaking changes could be made in patch releases, so fixing to 1.17.0 is the widest version constraint possible.

**Comment by GrahamCampbell** [comment]
> We don't need this polyfill as we install php-intl/ext-intl. 

You actually may need the polyfill still, which is the reason for us doing this... even if you have the extension loaded!

**Comment by Nyholm** [comment]
Thank you for this PR. 

https://github.com/guzzle/guzzle/pull/2672#issuecomment-640024468

**Pull request closed without merging**
