### PR TITLE
Fix example by adding backslash

### PR DESCRIPTION
**Pull request by JHGitty**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by GrahamCampbell** [comment]
Backslack not needed because the example is without a namespace.

**Comment by GrahamCampbell** [comment]
It's incorrect to add a bashslash when not inside a namespace.

**Comment by JHGitty** [comment]
But later in the same example there is a backslash used:
```php
$request = new \GuzzleHttp\Psr7\Request('GET', 'http://httpbin.org');
```

**Comment by GrahamCampbell** [comment]
Then I think we should remove that backslash.

**Comment by mtdowling** [comment]
Yeah I don't think this is necessary

**Pull request closed without merging**
