### PR TITLE
[Minor] Fixed typehint $transferTime of constructor

### PR DESCRIPTION
**Pull request by gmponos**

### CODE REVIEW

**Comment by wirwolf** [comment]
Hello @gmponos, i create a fork of this repo and release this marge request into the new version(6.4.0).

Namespace compatibility is 100%, and you can use my changes if you patch composer.json in your projects
* replace `"guzzlehttp/guzzle": "^6.3"` to `"someblackmagic/guzzle": "^6.4"` 
* add `"guzzlehttp/guzzle": "6.3.*"` into replace block

Fork link: https://github.com/SomeBlackMagic/guzzle/

**Comment by wirwolf** [comment]
@Nyholm i send this text in all MR in release

**Comment by Nyholm** [comment]
I know. That is why Im telling you to stop making noice. The past hour you have sent more than 15 000 emails with the same comment. 

You are event telling maintainers of Guzzle to use "someblackmagic". 

I would be super happy if you focus your energy to help pushing Guzzle to the next version instead. 
Maybe by creating an issue with change logs and make sure we dont have any nasty BC breaks. 
There are always plenty one can do. If unsure, open an issue, review a PR or answer issues.

**Comment by wirwolf** [comment]
@Nyholm 
I can not create the tag(release) in this repo. This the main problem why i create a fork. 
https://github.com/guzzle/guzzle/pull/2279#issuecomment-543608481

**Comment by Nyholm** [comment]
I know you cannot. Only maintainers can tag releases. But you can do much important and appreciated work without being a maintainer. 

I spent 3 hours now preparing a release. See #2374. 
I (and other maintainers) would much appreciate if you spent time doing all the awesome things you did in your fork in this repository. 

Also, read this: https://github.com/guzzle/guzzle/issues/2306#issuecomment-543638957

**Pull request merged**
