### PR TITLE
Added some basic PHPDoc to Client class

### PR DESCRIPTION
**Pull request by cebe**
Without this, IDE autocompletion does not work correctly. At least in PHPStorm.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: This is a duplicate and has already been rejected. You MUST NOT duplicate docblocks from interfaces. If phpstorm isn't working, then phpstorm is broken...

**Comment by cebe** [comment]
Found the issue for this: https://youtrack.jetbrains.com/issue/WI-23395
What about adding 

```php
/**
 * @inheritDoc
 */
```

until the issue is fixed?

**Comment by GrahamCampbell** [comment]
I don't think so. https://github.com/guzzle/guzzle/issues/872#issuecomment-59844746

**Comment by mtdowling** [comment]
Thanks for handling this for me, @GrahamCampbell :)

I appreciate the PR @cebe, but I don't like the duplication, and using @inheritdoc is a misuse of the tag. PHPStorm people say they're working on... The only problem there is it is slated for v9 which means everyone will have to pay that bugfix.

**Comment by cebe** [comment]
Thanks for the pointer to that issue. I fully agree that PHPStorm should fix the bug and support this.
Nevertheless  adding `@inheritdoc` does not hurt and makes the library more compatible and users more happy with it. I more often prefer to go the pracitcal way to make it work for everyone.
May I ask which IDE you are using?

**Pull request closed without merging**
