### PR TITLE
[7.1] Avoid global functions in dependencies

### PR DESCRIPTION
**Pull request by GrahamCampbell**
EDIT: The new aim of this PR is avoid the use of global functions provided by our dependencies. This means using their new Utils classes, and bumping their minimum versions (staying within the same major release series).

### CODE REVIEW

**Comment by Nyholm** [comment]
Could we support version 1 and 2 at the same time?

**Comment by GrahamCampbell** [comment]
Depends what we want to do with the functions.

**Comment by GrahamCampbell** [comment]
@Nyholm I wonder if I should add `Utils` classes to the 1.x versions of these two libraries, and deprecate the functions, and then remove them in 2.x? That way, we could easily support both versions, without needing 3.x to finally delete the functions?

**Comment by GrahamCampbell** [comment]
Or maybe even, to minimize BC, only add the `Utils` classes, but don't change the 1.x internals to calling them yet, and don't deprecate the functions yet. Then make the internal changes in 2.0, deprecations in 2.1, and removals in 3.0?

**Comment by GrahamCampbell** [comment]
> Could we support version 1 and 2 at the same time?

New plan: only update to `guzzlehttp/promises:^1.4` and `guzzlehttp/psr7:^1.7` in this PR, using the new `Utils` classes.

**Comment by Nyholm** [comment]
Sound good!

**Comment by GrahamCampbell** [comment]
Whoops, all my PRs seem to have become detached after I accidentally deleted my fork instead of a different one. I still have all my code locally, but it looks like I will need to re-create all the PRs. 😆

**Pull request closed without merging**
