### PR TITLE
fix dash underline for idn_conversion

### PR DESCRIPTION
**Pull request by jonnott**
...so it actually shows up as a section in the docfile

### CODE REVIEW

**Comment by jonnott** [comment]
Submitted a new PR for 6.5 branch as well as master..

**Comment by sagikazarmark** [comment]
@jonnott I can't see your PR submitted to master. Can you please send this patch there too?

Thanks!

**Comment by jonnott** [comment]
> @jonnott I can't see your PR submitted to master. Can you please send this patch there too?
> 
> Thanks!

Sorry, I had closed it ..

https://github.com/guzzle/guzzle/pull/2460

**Comment by jonnott** [comment]
> > @jonnott I can't see your PR submitted to master. Can you please send this patch there too?
> > Thanks!
> 
> Sorry, I had closed it ..
> 
> #2460

@sagikazarmark

**Pull request merged**
