### PR TITLE
Automated native_function_invocation fixes

### PR DESCRIPTION
**Pull request by draco2003**
Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix src --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)

Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

### CODE REVIEW

**Comment by Nyholm** [comment]
I agree with this change. But we cannot do it since the tests rely on overwriting some custom functions.

**Comment by gmponos** [comment]
How about using the `compiler_optimized` option?

https://mlocati.github.io/php-cs-fixer-configurator/#version:2.16|fixer:native_function_invocation

**Comment by gmponos** [comment]
Not sure about this but I think namespacing every function has a misbenefit.. symfony is also using the compiler optimized... if I understood correctly this ruleset: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.16/src/RuleSet.php#L195

**Comment by Nyholm** [comment]
Fixed in #2444

**Pull request closed without merging**
