### PR TITLE
Update Client.php

### PR DESCRIPTION
**Pull request by jaylathia**
Adding preg_replace to replace square braces of array indices, generated by http_build_query function.

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. I do not understand why you would like to replace them. Can you please explain your scenario. 

Aslo, if this PR ever going to get merged there has to be tests.

**Comment by jaylathia** [comment]
The scenario being converting 
`?variable[0]=value1&variable[1]=value2&variable[2]=value3`
to
`?variable=value1&variable=value2&variable=value3`

**Comment by Nyholm** [comment]
Yes, I can see that your patch converts the query like that.

`?variable=value1&variable=value2&variable=value3` is not a valid format for a query string. That is why I asked why you would like this change.

**Comment by jayS-de** [comment]
It is a valid query string. But it depends on the library/language you are using if this could be correctly parsed.

Most PHP applications expect the array notation. In other languages its very common to combine parameters of the same name. The URI implementation is able to parse this correctly.

**Comment by sagikazarmark** [comment]
Putting this onto my close in a few days list.

**Comment by mtdowling** [comment]
This is a breaking change. You can provide the query option as a string to use any form of serialization you'd like.

**Comment by sagikazarmark** [comment]
Closing as:

- breaking change
- alternative solution proposed
- invalid

**Pull request closed without merging**
