### PR TITLE
rewind response body after format

### PR DESCRIPTION
**Pull request by wjfz**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR, but we should not be trying to do this.

**Comment by wjfz** [comment]
@GrahamCampbell 
I think it's a bit necessary. If somebody set a log middleware to response body and the response status code >= 400, the exception can't get the body summary because it's not rewind.

https://github.com/guzzle/psr7/blob/13388f00956b1503577598873fffb5ae994b5737/src/Message.php#L70

**Comment by GrahamCampbell** [comment]
Oh, I think it's that message code that should probably do the re-wind.

**Comment by GrahamCampbell** [comment]
https://github.com/guzzle/psr7/pull/525

**Comment by wjfz** [comment]
Thank you, solve my problem, but i still puzzle about this.
If someone use the formatter in middware to log each response or do something else, the formatter read the response body but not rewind it, it's  destructive.
I think who use it, who restore it maybe better?

**Comment by GrahamCampbell** [comment]
For small streams, people mostly consume them by casting them to a string, which automatically rewinds. A common mistake is to call `->getContent()`. If you must do a method call, do `->__toString()`.

**Comment by wjfz** [comment]
Thank you for your reply.

**Pull request closed without merging**
