### PR TITLE
Apply PSR2

### PR DESCRIPTION
**Pull request by omarkdev**

### CODE REVIEW

**Comment by localheinz** [comment]
Rather than manually applying the changes, what do you think about leveraging one of 

* [`friendsofphp/php-cs-fixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer)
* [`squizlabs/php_codesniffer`](https://github.com/squizlabs/PHP_CodeSniffer)

?

**Comment by sagikazarmark** [comment]
It's on the todolist, but that would make lots of PRs conflicting.

**Comment by gmponos** [comment]
> It's on the todolist, but that would make lots of PRs conflicting.

Then there will never be a good time to do so.

**Comment by sagikazarmark** [comment]
Right, but the PHP 7 and PSR-18 upgrade will also be a huge upgrade, so I planned to time applying the PHP CS fixer to that date.

**Comment by gmponos** [comment]
Having on CI (travis) the checks about codestyle wont this save you some review time from these huge upgrades? And as far as I know according to the public development that I see from PRs on github the progress for applying PSR-18 and PHP 7 is a not that big... maybe I am wrong.

Sorry if I push stuff... that's not my intention but I believe it would be better to have a set of rules and enforce them through CI, rather than having these huge upgrades and having more changes later on. Anyway I stop here.. your decision at the end of the day.

**Comment by localheinz** [comment]
@sagikazarmark 

Then let's get these PRs merged! Please let us know if we can help move forward! 🤓

**Comment by sagikazarmark** [comment]
Thanks @omarkdev @localheinz . This will be fixed when I get to #2239

**Pull request closed without merging**
