### PR TITLE
The CurlMultiHandle causes a busy immediately when the first byte is received

### PR DESCRIPTION
**Pull request by frodeborli**
I've provided a patch to the CurlMultiHandler which leverages the event loop. This allows TaskQueue implementations to properly sleep between each invocation of the \curl_multi_exec, and added a curl_multi_select() statement inside the busy wait loop that is meant to "wrap up" things.

### CODE REVIEW

**Comment by frodeborli** [comment]
I'm not sure what I can do with the PHPStan tests. They seem to be unrelated to my patch.

**Comment by GrahamCampbell** [comment]
It's probably because you ran composer and phpstan with a different version of PHP. ~You'd need to use our Makefile. e.g. `make static-psalm-update-baseline`.~ You need to use PHP 7.4.

**Comment by frodeborli** [comment]
I made the commit to the 7.8 branch. Should I also make it for the 7.9 and 8.0?

**Comment by GrahamCampbell** [comment]
> I made the commit to the 7.8 branch. Should I also make it for the 7.9 and 8.0?

No.

**Comment by GrahamCampbell** [comment]
I'm still aware of of this PR, and appreciate the time you took to prepare this. I'm hoping to get to this soon, so this can be included in the next release(s).

**Comment by GrahamCampbell** [comment]
Thanks for working on this. Moving this to #3234.

**Pull request closed without merging**
