### PR TITLE
Remove the need for `AllowDynamicProperties` in CurlMultiHandler

### PR DESCRIPTION
**Pull request by TimWolla**
see guzzle/psr7#547

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Heh. Can you re-gen the psalm baseline plz - I'm happy that we just make it stfu for these changes for now. ;)

**Comment by TimWolla** [comment]
Okay, I have no idea what I did wrong, but CI still is red.

It was not easy to get PHPStan and Psalm working in the first place, because apparently they are broken on PHP 8.2 (and also complain when executed with PHP 7.4 like in CI).

**Comment by TimWolla** [comment]
@GrahamCampbell Got it to work, CI is green now.

**Comment by GrahamCampbell** [comment]
image

**Pull request merged**
