### PR TITLE
[7.0] Added real client methods

### PR DESCRIPTION
**Pull request by GrahamCampbell**
So, maybe we have consensus for this plan now:

1. We merge this PR before the 7.0.0 release.
2. We merge https://github.com/guzzle/guzzle/pull/2482 for the 7.1.0 release.
3. We remove __call in 8.0.0.

---

It remains to be discussed what to do with the ClientInterface.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Adding these methods isn't any kind of break, so we are free to do it in 7.0

**Comment by GrahamCampbell** [comment]
> Adding these methods isn't any kind of break, so we are free to do it in 7.0

Adding these is a break, if people are extending the class.

We have already made a BC break since the 7.0.0 beta1, so more breaks are fine. I assume we will stop making breaks once we get to either RC or stable?

**Comment by GrahamCampbell** [comment]
I've added a note to the upgrading guide.

**Comment by sagikazarmark** [comment]
> Adding these is a break, if people are extending the class.

Well, only if someone implemented these methods with a different signature, but I'm not so concerned about that. Also, extending the `Client` class is not something that people should do (even if it's not marked as final).

But yeah, strictly speaking it CAN be a break in certain cases, but it's not a break in behavior.

**Pull request merged**
