### PR TITLE
Unpin version for symfony/polyfill-intl-idn

### PR DESCRIPTION
**Pull request by Nyholm**
As an alternative to https://github.com/guzzle/guzzle/pull/2663

### CODE REVIEW

**Comment by gmponos** [comment]
I can approve if you wish.. but I don't have strong arguments for one approach vs the other... if you do.. or if this is what your guts tell you is right.. let's proceed

**Comment by GrahamCampbell** [comment]
I'd be against this PR since the 6.x branch is supposed to "just work", regardless of what extensions are installed or what version of the polyfill is loaded.

**Comment by Nyholm** [comment]
> the 6.x branch is supposed to "just work"

I agree. 

-----

Comparing this PR with https://github.com/guzzle/guzzle/pull/2663: 

1. Both will "just work" in 99% of cases. 
2. This PR will "not work" if someone incorrectly "replaced symfony idn polyfill"
3. https://github.com/guzzle/guzzle/pull/2663 will "not work" when someone replaced incorrectly "symfony mbstring polyfill"

Both 2 and 3 are super rare. But this PR is simpler than #2663. 

Is there anything else that differs the PRs?

**Comment by GrahamCampbell** [comment]
> Both will "just work" in 99% of cases.

Well, no. This PR will fail for a lot of people if symfony do change the class. The other PR will always work 100% of the time for everyone.

**Comment by GrahamCampbell** [comment]
> #2663 will "not work" when someone replaced incorrectly "symfony mbstring polyfill"

No, it would still work fine.

**Comment by GrahamCampbell** [comment]
Also, this PR uses the mbstring polyfill too...

**Comment by gmponos** [comment]
We can always go back from one or the other solution.. it has also it's downsides not including the polyfill as we will need to follow the fixes of `sf`.. I was in favor with the solution implemented here.. but I can't say that my arguments are STRONG enough... so I will stick with what I had first in mind. :)

**Comment by Nyholm** [comment]
> Well, no. This PR will fail for a lot of people if symfony do change the class.

So in an application that has replaced `symfony/polyfill-intl-idn` with an old version of intl AND Symfony changed that class and method, then yes, that application will get an exception when running their tests. 

 Since we are not locking ourselves in with this solution, I would like to merge it and focus on 7.

**Comment by GrahamCampbell** [comment]
> I would like to merge it and focus on 7.

I'd like to merge the other PR and focus on 7. The other PR genuinely makes this done and duster forever. No possibility that anything could break in the future.

**Comment by GrahamCampbell** [comment]
And it fixes the problem with bad replacement.

**Comment by Nyholm** [comment]
> No possibility that anything could break in the future.

That is not true. We got more code to maintain ourselves. See https://github.com/symfony/polyfill/issues/159

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
